[package]
name = "rust_math"
version = "0.1.0"
edition = "2021"
authors = ["Başar Kaman <bktech2021@outlook.com>"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
